/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package capavista;

import capamodel.Punt;
import capamodel.Ruta;
import static capavista.Login.gBD;
import static capavista.Login.u;
import java.awt.Component;
import java.awt.Container;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import static capavista.Rutes.punts;
import java.awt.event.ActionEvent;

/**
 *
 * @author Juan Antonio
 */
public class CrearRuta extends javax.swing.JFrame {

    /**
     * Creates new form CrearRuta
     */
    
    
    public CrearRuta() {
        initComponents();
        setTitle("WikiLoc Juan Antonio");
        
        
        //dificultatCombo.setModel();
        
        dificultatCombo.addItem(" ");
        dificultatCombo.addItem("1 - Facil");
        dificultatCombo.addItem("2 - Moderat");
        dificultatCombo.addItem("3 - Dificil");
        dificultatCombo.addItem("4 - Molt dificil");
        dificultatCombo.addItem("5 - Nomes experts");
        
        //table de punts: 
        //tabe primer cop:
        //titol data propietari distancia dificultat desnivell Punts Valoracions
        
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("Nom");
        tableModel.addColumn("Descripcio");
        tableModel.addColumn("Lat");
        tableModel.addColumn("Lon");
        tableModel.addColumn("Alt");
        tableModel.addColumn("Tipus");

        // Agregar filas de datos al modelo
        if(punts != null){
            for(Punt p : punts){
                tableModel.addRow(new Object[]{p.getNom(), p.getDescripcio(), p.getLat(), p.getLon(), p.getAlt(), p.getTipus().getNom()});
            }
        }
        tablePunts.setModel(tableModel);
        this.addFocusListener(new FocusListener(){
            @Override
            public void focusGained(FocusEvent e){
                //Eliminar les entrades per actualitzar els punts;
                int rowCount = tablePunts.getRowCount();
                for (int i = rowCount - 1; i >= 0; i--) {
                    tableModel.removeRow(i);
                }
                
                if(punts != null){
                    for(Punt p : punts){
                        tableModel.addRow(new Object[]{p.getNom(), p.getDescripcio(), p.getLat(), p.getLon(), p.getAlt(), p.getTipus().getNom()});
                    }
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                //
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textFormatArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        descriptionArea = new javax.swing.JTextArea();
        titolField = new javax.swing.JTextField();
        distanciaSpinner = new javax.swing.JSpinner();
        desnnSpinner = new javax.swing.JSpinner();
        desnpSpinner = new javax.swing.JSpinner();
        dificultatCombo = new javax.swing.JComboBox<>();
        crearButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablePunts = new javax.swing.JTable();
        addPunt = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        LogOutButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        buttonModPunt = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();
        tempsSpinner = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Punts");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Crear Ruta");

        jLabel3.setText("Titol:");

        jLabel4.setText("Descripció:");

        jLabel5.setText("Text amb format: ");

        jLabel6.setText("Distancia:");

        jLabel7.setText("Desnivell positiu: ");

        jLabel8.setText("Desnivell negatiu: ");

        jLabel9.setText("Dificultat: ");

        textFormatArea.setColumns(20);
        textFormatArea.setRows(5);
        jScrollPane1.setViewportView(textFormatArea);

        descriptionArea.setColumns(20);
        descriptionArea.setRows(5);
        jScrollPane2.setViewportView(descriptionArea);

        crearButton.setText("Crear ruta");
        crearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearButtonActionPerformed(evt);
            }
        });

        tablePunts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tablePunts);

        addPunt.setText("Afegir Punt");
        addPunt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPuntActionPerformed(evt);
            }
        });

        homeButton.setText("Les meves rutes");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        LogOutButton.setText("Log out");
        LogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutButtonActionPerformed(evt);
            }
        });

        jLabel10.setText("m");

        jLabel11.setText("Temps");

        buttonModPunt.setText("Modificar Punt");
        buttonModPunt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModPuntActionPerformed(evt);
            }
        });

        errorLabel.setForeground(java.awt.Color.red);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9))
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(crearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(dificultatCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, 142, Short.MAX_VALUE)
                                            .addComponent(distanciaSpinner, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(desnpSpinner, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(desnnSpinner, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tempsSpinner))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(42, 42, 42))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                            .addComponent(titolField))))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addPunt, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(buttonModPunt, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(401, 401, 401)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LogOutButton)
                .addGap(31, 31, 31))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(jLabel2)
                    .addContainerGap(1145, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(homeButton)
                    .addComponent(LogOutButton))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel6)
                                            .addComponent(distanciaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7)
                                            .addComponent(desnpSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel8)
                                            .addComponent(desnnSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(dificultatCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(titolField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11))
                            .addComponent(tempsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addPunt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonModPunt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(jLabel2)
                    .addContainerGap(663, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addPuntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPuntActionPerformed
        // TODO add your handling code here:
        CrearPunt crearPunt = new CrearPunt(this);
        setFocusableWindowState(false);
        setFocusable(false);
        disableAllComponents(this);
        crearPunt.setVisible(true);
    }//GEN-LAST:event_addPuntActionPerformed

    private static void disableAllComponents(Container container) {
        Component[] components = container.getComponents();
        for (Component component : components) {
            if (component instanceof Container) {
                // Si es un contenedor, deshabilitar sus componentes también
                disableAllComponents((Container) component);
            }
            component.setEnabled(false);
        }
    }
    
    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        Rutes r = new Rutes(u);
        r.setVisible(true);
        dispose();
    }//GEN-LAST:event_homeButtonActionPerformed

    private void LogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutButtonActionPerformed
        // TODO add your handling code here:
        Login l = new Login();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogOutButtonActionPerformed

    private void crearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearButtonActionPerformed
        // TODO add your handling code here:
        Ruta r = new Ruta();
        boolean create = true;
        String errorText = "";
        //control de error: 
        if(titolField.getText().trim().length() < 3){
            create = false;
            errorText = "El titol ha de tenir més de tres lletres";
        }
        if((distanciaSpinner.getValue()+"").length() > 6){
            create = false;
            errorText = "La distancia no pot ser tan llarga";
        }
        if ( (int) distanciaSpinner.getValue() <= 0 ){
            create = false;
            errorText = "La distancia ha de ser mes llarga";
        }
        if((int)desnpSpinner.getValue() > 9999){
            create = false;
            errorText = "El denivell positiu ha de ser mes petit";
        }
        if((int)desnnSpinner.getValue() > 9999){
            create = false;
            errorText = "El denivell negatiu ha de ser mes petit";
        }
        
        if(dificultatCombo.getSelectedIndex() == 0){
            create = false;
            errorText = "Has de seleccionar una dificulatat valida";
        }
        if((int) tempsSpinner.getValue() <= 0){
            create = false;
            errorText = "El temps ha de ser un numero enter positiu";
        }
        
        if(!create){
            Error e = new Error(this, true, errorText);
            e.setVisible(true);
        }else{
            r.setTitol(titolField.getText().trim());
            r.setDescripcio(descriptionArea.getText().trim());
            r.setPropietari(u);
            r.setTexthtml(textFormatArea.getText().trim());
            r.setDistancia(Float.parseFloat(""+distanciaSpinner.getValue()));
            r.setDesn_p((int)desnpSpinner.getValue());
            r.setDesn_n((int) desnnSpinner.getValue());

            String dif = (String) dificultatCombo.getSelectedItem();
            r.setDificultat(Integer.parseInt(dif.charAt(0)+""));

            r.setTime(Integer.parseInt(""+tempsSpinner.getValue()));

            Date data = new Date();
            r.setData(data);
        
        
            int id = gBD.afegirRuta(r);
            r.setId(id);
            System.out.println("ruta id: "+r.getId());
            if(punts != null){
                for(Punt p: punts){
                    p.setRuta(r);
                    gBD.afegirPunt(p);
                }
            }
            gBD.confirmarCanvis();
            punts = null;
            punts = new ArrayList();

            Rutes rutesVista = new Rutes(u);
            rutesVista.setVisible(true);
            dispose();
        }
        
        
    }//GEN-LAST:event_crearButtonActionPerformed

    private void buttonModPuntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModPuntActionPerformed
        // TODO add your handling code here:
        errorLabel.setText(" ");
        System.out.println("Selected Row: "+ tablePunts.getSelectedRow()+ " Punts.length: "+punts.size());
        if(tablePunts.getSelectedRow() != -1){
            ModificarPunt modPunt = new ModificarPunt(this, tablePunts.getSelectedRow());
            
            setFocusableWindowState(false);
            setFocusable(false);
            disableAllComponents(this);
            
            modPunt.setVisible(true);
        }else{
            errorLabel.setText("Has de seleccionar un punt");
        }
    }//GEN-LAST:event_buttonModPuntActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearRuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearRuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearRuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearRuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearRuta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogOutButton;
    private javax.swing.JButton addPunt;
    private javax.swing.JButton buttonModPunt;
    private javax.swing.JButton crearButton;
    private javax.swing.JTextArea descriptionArea;
    private javax.swing.JSpinner desnnSpinner;
    private javax.swing.JSpinner desnpSpinner;
    private javax.swing.JComboBox<String> dificultatCombo;
    private javax.swing.JSpinner distanciaSpinner;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tablePunts;
    private javax.swing.JSpinner tempsSpinner;
    private javax.swing.JTextArea textFormatArea;
    private javax.swing.JTextField titolField;
    // End of variables declaration//GEN-END:variables

    

}
