/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package capavista;

import capamodel.Punt;
import capamodel.Ruta;
import static capavista.Login.gBD;
import static capavista.Login.u;
import static capavista.Rutes.punts;
import java.awt.Component;
import java.awt.Container;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Date;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juan Antonio
 */
public class ModificarRuta extends javax.swing.JFrame {

    /**
     * Creates new form CrearRuta
     */
    
    private Ruta ruta_mod = null;
    public ModificarRuta(Ruta ruta) {
        initComponents();
        setTitle("WikiLoc Juan Antonio");
        //table de punts: 
        //tabe primer cop:
        //titol data propietari distancia dificultat desnivell Punts Valoracions
        
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("Nom");
        tableModel.addColumn("Descripcio");
        tableModel.addColumn("Lat");
        tableModel.addColumn("Lon");
        tableModel.addColumn("Alt");
        tableModel.addColumn("Tipus");

        // Agregar filas de datos al modelo
        
        punts = (ArrayList) gBD.obtenirLlistaPuntsRuta(ruta);
        if(punts != null){
            for(Punt p : punts){
                tableModel.addRow(new Object[]{p.getNom(), p.getDescripcio(), p.getLat(), p.getLon(), p.getAlt(), p.getTipus().getNom()});
            }
        }
        tablePunts.setModel(tableModel);
        
        
        //afegir camps de modificar ruta:
        ruta_mod = ruta;
        System.out.println("Ruta modificar: " + ruta_mod.getId());
        titolField.setText(ruta.getTitol());
        descripcioArea.setText(ruta.getDescripcio());
        formatArea.setText(ruta.getTexthtml());
        distanciaSpinner.setValue(ruta.getDistancia());
        positiuSpinner.setValue(ruta.getDesn_p());
        negatiuSpinner.setValue(ruta.getDesn_n());
        tempsSpinner.setValue(ruta.getTime());
        
        //dificultatCombo.setModel();
        
        dificultatCombo.addItem(" ");
        dificultatCombo.addItem("1 - Facil");
        dificultatCombo.addItem("2 - Moderat");
        dificultatCombo.addItem("3 - Dificil");
        dificultatCombo.addItem("4 - Molt dificil");
        dificultatCombo.addItem("5 - Nomes experts");        
        
        dificultatCombo.setSelectedIndex(ruta.getDificultat());
        
        this.addFocusListener(new FocusListener(){
            @Override
            public void focusGained(FocusEvent e){
                //Eliminar les entrades per actualitzar els punts;
                int rowCount = tablePunts.getRowCount();
                for (int i = rowCount - 1; i >= 0; i--) {
                    tableModel.removeRow(i);
                }
                
                if(punts != null){
                    for(Punt p : punts){
                        tableModel.addRow(new Object[]{p.getNom(), p.getDescripcio(), p.getLat(), p.getLon(), p.getAlt(), p.getTipus().getNom()});
                    }
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                
            }
        
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        formatArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        descripcioArea = new javax.swing.JTextArea();
        titolField = new javax.swing.JTextField();
        distanciaSpinner = new javax.swing.JSpinner();
        negatiuSpinner = new javax.swing.JSpinner();
        positiuSpinner = new javax.swing.JSpinner();
        dificultatCombo = new javax.swing.JComboBox<>();
        crearButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablePunts = new javax.swing.JTable();
        addPunt = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        JLabel10 = new javax.swing.JLabel();
        buttonModPunt = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();
        tempsSpinner = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Punts");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Modificar Ruta");

        jLabel3.setText("Titol:");

        jLabel4.setText("Descripció:");

        jLabel5.setText("Text amb format: ");

        jLabel6.setText("Distancia:");

        jLabel7.setText("Desnivell positiu: ");

        jLabel8.setText("Desnivell negatiu: ");

        jLabel9.setText("Dificultat: ");

        formatArea.setColumns(20);
        formatArea.setRows(5);
        jScrollPane1.setViewportView(formatArea);

        descripcioArea.setColumns(20);
        descripcioArea.setRows(5);
        jScrollPane2.setViewportView(descripcioArea);

        crearButton.setText("Confirmar canvis");
        crearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearButtonActionPerformed(evt);
            }
        });

        tablePunts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tablePunts);

        addPunt.setText("Afegir Punt");
        addPunt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPuntActionPerformed(evt);
            }
        });

        jButton1.setText("Les meves rutes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Log out");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        JLabel10.setText("Temps:");

        buttonModPunt.setText("Modificar Punt");
        buttonModPunt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModPuntActionPerformed(evt);
            }
        });

        errorLabel.setForeground(java.awt.Color.red);

        jLabel12.setText("metres");

        jLabel14.setText("metres");

        jLabel13.setText("metres");

        jLabel10.setText("minuts");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9))
                            .addComponent(JLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(crearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(dificultatCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, 142, Short.MAX_VALUE)
                                            .addComponent(distanciaSpinner, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(positiuSpinner, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(negatiuSpinner, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tempsSpinner))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(36, 36, 36))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(titolField))))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addPunt, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(buttonModPunt, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(401, 401, 401)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(31, 31, 31))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(jLabel2)
                    .addContainerGap(1101, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel6)
                                                    .addComponent(distanciaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel7)
                                                    .addComponent(positiuSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel14))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel8)
                                                    .addComponent(negatiuSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel13)))
                                            .addComponent(jLabel12))
                                        .addGap(22, 22, 22)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(dificultatCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(titolField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLabel10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tempsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)))))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addPunt, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(buttonModPunt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(jLabel2)
                    .addContainerGap(656, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addPuntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPuntActionPerformed
        // TODO add your handling code here:
        CrearPunt crearPunt = new CrearPunt(this);
        setFocusableWindowState(false);
        setFocusable(false);
        disableAllComponents(this);
        crearPunt.setVisible(true);
    }//GEN-LAST:event_addPuntActionPerformed

    private static void disableAllComponents(Container container) {
        Component[] components = container.getComponents();
        for (Component component : components) {
            if (component instanceof Container) {
                // Si es un contenedor, deshabilitar sus componentes también
                disableAllComponents((Container) component);
            }
            component.setEnabled(false);
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Rutes r = new Rutes(u);
        r.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Login l = new Login();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void crearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearButtonActionPerformed
        // TODO add your handling code here:
        Ruta r = new Ruta();
        boolean create = true;
        String errorText = "";
        //control de error: 
        if(titolField.getText().trim().length() < 3){
            create = false;
            errorText = "El titol ha de tenir més de tres lletres";
        }
        if((distanciaSpinner.getValue()+"").length() > 6){
            create = false;
            errorText = "La distancia no pot ser tan llarga";
        }
        if ( Float.parseFloat(""+distanciaSpinner.getValue()) <= 0 ){
            create = false;
            errorText = "La distancia ha de ser mes llarga";
        }
        if((int)positiuSpinner.getValue() > 9999){
            create = false;
            errorText = "El denivell positiu ha de ser mes petit";
        }
        if((int)negatiuSpinner.getValue() > 9999){
            create = false;
            errorText = "El denivell negatiu ha de ser mes petit";
        }
        
        if(dificultatCombo.getSelectedIndex() == 0){
            create = false;
            errorText = "Has de seleccionar una dificulatat valida";
        }
        if( Integer.parseInt(""+tempsSpinner.getValue()) <= 0){
            create = false;
            errorText = "El temps ha de ser un numero enter positiu";
        }
        
        if(!create){
            Error e = new Error(this, true, errorText);
            e.setVisible(true);
        }else{
            r.setId(ruta_mod.getId());
            r.setTitol(titolField.getText().trim());
            r.setDescripcio(descripcioArea.getText().trim());
            r.setPropietari(u);
            r.setTexthtml(formatArea.getText().trim());
            r.setDistancia(Float.parseFloat(""+distanciaSpinner.getValue()));
            r.setDesn_p((int) positiuSpinner.getValue());
            r.setDesn_n((int) negatiuSpinner.getValue());

            String dif = (String) dificultatCombo.getSelectedItem();
            r.setDificultat(Integer.parseInt(dif.charAt(0)+""));

            r.setTime( Integer.parseInt(""+tempsSpinner.getValue()));

            Date data = new Date();
            r.setData(data);
            gBD.actualitzarRuta(r);

            //System.out.println("ruta id: "+r.getId());
            if(punts != null){
                //control de numeros per poder insertar en la base de dades;
                Collections.sort(punts, Comparator.comparingInt(Punt::getNum));
                int i = 1;
                for(Punt p: punts){
                    p.setNum(i);
                    i++;
                    p.setRuta(r);
                    if(p.getDescripcio() == null){
                        p.setDescripcio("");
                    }
                    if(p.getId() == -1){
                        gBD.afegirPunt(p);
                    }else{
                        gBD.actualitzarPunt(p);
                    }
                }
            }
            gBD.confirmarCanvis();
            punts = null;
            punts = new ArrayList();

            Rutes rutesVista = new Rutes(u);
            rutesVista.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_crearButtonActionPerformed

    private void buttonModPuntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModPuntActionPerformed
        // TODO add your handling code here:
        errorLabel.setText(" ");
        System.out.println("Selected Row: "+ tablePunts.getSelectedRow()+ " Punts.length: "+punts.size());
        if(tablePunts.getSelectedRow() != -1){
            ModificarPunt modPunt = new ModificarPunt(this, tablePunts.getSelectedRow());
            
            setFocusableWindowState(false);
            setFocusable(false);
            disableAllComponents(this);
            
            modPunt.setVisible(true);
        }else{
            errorLabel.setText("Has de seleccionar un punt");
        }
    }//GEN-LAST:event_buttonModPuntActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel10;
    private javax.swing.JButton addPunt;
    private javax.swing.JButton buttonModPunt;
    private javax.swing.JButton crearButton;
    private javax.swing.JTextArea descripcioArea;
    private javax.swing.JComboBox<String> dificultatCombo;
    private javax.swing.JSpinner distanciaSpinner;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JTextArea formatArea;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner negatiuSpinner;
    private javax.swing.JSpinner positiuSpinner;
    private javax.swing.JTable tablePunts;
    private javax.swing.JSpinner tempsSpinner;
    private javax.swing.JTextField titolField;
    // End of variables declaration//GEN-END:variables
}
